### ISSUE TITLE
Loose parts?

### ISSUE THREAD

**Issue by Bluelight82** [EGO-Tech/starbase-ships#48]
![image](https://user-images.githubusercontent.com/56890243/178689525-c465d109-95f8-4ae6-aae3-aedeee215187.png)
Loose parts?

**Comment by vinteo** [comment]
Depending on your PC it takes a while to fully load, wait a couple of mins
after you open the BP before trying to print

**Comment by Bluelight82** [comment]
I re-downloaded the BP and loaded it again and then it worked!
