### ISSUE TITLE
Material Point Scanner on Rigger functions incorrectly due to a shared variable.

### ISSUE THREAD

**Issue by BGASM** [EGO-Tech/starbase-ships#95]
Material Scanner will not point toward rangefinder without small tweak.

```
1. Rename 'sp' to 'spc' on the material scanner turret itself
2. Add 'spc' to one of the four memory chips
3. Update line 4 of the scanner yolo to:
d=:Distance+x if:Distance>0thend=y/d*r end :spc=d
```

The reason I could find is the **speedometer**. The speedometer part has a device parameter 'sp'. 

I don't know if this is stock, or from a recent update to the game or to the ship blueprint. But, this is the issue causing the material scanner to pitch up and down wildly and unable to scan unless touching an asteroid. 

I left the pre-existing variable 'sp' on the memory card because I wasn't sure if it had other uses in other yolo code.

**Comment by vinteo** [comment]
Thank you for reporting this, this may have been from the most recent update.

Unfortunately I am on holiday and will only be back in Feb so I will fix the BP when I get back. But your steps should fix it. I am not sure step 2 is needed but it wouldn't cause any issues with it.

**Comment by wasakoki** [comment]
i downloaded the bp in the past week and built the ship, it seems like line 4 on the scanner YOLOL chip on the blueprint itself still points to the sp variable. i had to fix mine by swapping the variable to mp to get the tracking functional.

**Comment by vinteo** [comment]
@wasakoki  thanks for reporting. I was pretty sure I did it last time so I loaded it again and saw it wasn't changed so I changed it and saved then reloaded and it wasn't changed still!! But it worked after I changed, saved and reloaded again. Not sure what happened before. But hopefully it's fixed now.
